import { promises as fs } from "fs";
import path from "path";
import { readProjects } from "./projects-store";
import { listTasks, Task } from "./tasks-store";
import { withLock } from "./mutex";

/**
 * TEAM STATUS — the agent's window into the timeclock + task system.
 *
 * Same philosophy as PROJECT-TRACKER.md: the web app owns the authoritative
 * data (clock sessions live in the attendee app, tasks live here), so it
 * writes a compact markdown digest to the shared Drive. The agent reads the
 * FILE on demand — zero tokens until a user actually asks "who is working on
 * X" / "who is standby" / "what is Raffael doing".
 *
 * Regenerated every few minutes (boot + interval) and after task changes.
 * Location: TEAM_STATUS_PATH env, default /gdrive/SUPERPIXEL/TEAM-STATUS.md.
 */

const TEAM_STATUS_PATH =
  process.env.TEAM_STATUS_PATH ??
  path.posix.join(process.env.DRIVE_MOUNT_DIR ?? "/gdrive", "SUPERPIXEL", "TEAM-STATUS.md");

export function teamStatusPath(): string {
  return TEAM_STATUS_PATH;
}

interface MemberPulse {
  userKey: string;
  name: string;
  active: { projectId: string; inAt: string; breakAt?: string } | null;
  todayMs: number;
  weekMs: number;
  lastSeen: string | null;
  weekByProject: { projectId: string; ms: number }[];
}

const OFFSET_MIN = Number(process.env.TIMECLOCK_TZ_OFFSET_MIN ?? "480"); // WITA

const fmtH = (ms: number) => {
  const h = Math.floor(ms / 3600_000);
  const m = Math.floor((ms % 3600_000) / 60_000);
  return h > 0 ? `${h}h ${m}m` : `${m}m`;
};

const studioTime = (iso: string) =>
  new Date(Date.parse(iso) + OFFSET_MIN * 60_000).toISOString().slice(11, 16);

const studioDay = (iso: string) =>
  new Date(Date.parse(iso) + OFFSET_MIN * 60_000).toISOString().slice(0, 10);

interface DayAttendance {
  date: string;
  members: { userKey: string; name: string; ms: number; projects: string[] }[];
}

async function clockGet<T>(path: string): Promise<T | null> {
  const base = (process.env.TIMECLOCK_URL ?? "http://attendee-ui:3000").replace(/\/$/, "");
  const token = process.env.INTERNAL_TOKEN;
  if (!token) return null;
  try {
    const res = await fetch(`${base}${path}`, {
      headers: { "x-internal-token": token },
      cache: "no-store",
      signal: AbortSignal.timeout(10_000),
    });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

const fetchPulse = async (): Promise<MemberPulse[] | null> =>
  (await clockGet<{ members: MemberPulse[] }>("/api/timeclock/overview"))?.members ?? null;

const fetchDaily = async (): Promise<DayAttendance[] | null> =>
  (await clockGet<{ days: DayAttendance[] }>("/api/timeclock/daily?days=30"))?.days ?? null;

export async function updateTeamStatus(): Promise<void> {
  await withLock("team-status", async () => {
    try {
      const [projects, members, daily] = await Promise.all([
        readProjects(),
        fetchPulse(),
        fetchDaily(),
      ]);
      const pname = (id: string) =>
        projects.find((p) => p.id === id)?.name ?? "a deleted project";

      const tasksByProject = new Map<string, Task[]>();
      for (const p of projects) {
        tasksByProject.set(p.id, await listTasks(p.id));
      }
      const openTasks = [...tasksByProject.values()]
        .flat()
        .filter((t) => t.status !== "done");

      const lines: string[] = [
        "# SuperPixel Team Status",
        "",
        "Auto-generated by the assistant web app — do not edit. Read this file",
        "when asked WHO is working on something, who is STANDBY/free, what",
        "someone's tasks are, project schedules/milestones, or who was ACTIVE",
        "on a PAST DATE (see the Attendance section, last 30 days).",
        `Last updated: ${new Date().toISOString()} (times below are studio time, UTC+${OFFSET_MIN / 60}).`,
        "",
        "## Right now",
        "",
      ];

      if (!members) {
        lines.push("_Clock data unavailable at last update — rely on task assignments below._", "");
      } else {
        const working = members.filter((m) => m.active);
        const standby = members.filter((m) => !m.active);
        lines.push("### Working");
        if (working.length === 0) lines.push("- nobody is clocked in right now");
        for (const m of working) {
          lines.push(
            `- ${m.name} — ${pname(m.active!.projectId)} (since ${studioTime(m.active!.inAt)}, ${fmtH(
              m.todayMs
            )} today)${m.active!.breakAt ? ` — ON BREAK since ${studioTime(m.active!.breakAt)}` : ""}`
          );
        }
        lines.push("", "### Standby (not clocked in)");
        if (standby.length === 0) lines.push("- everyone is clocked in");
        for (const m of standby) {
          lines.push(
            `- ${m.name} — last seen ${
              m.lastSeen ? `${studioDay(m.lastSeen)} ${studioTime(m.lastSeen)}` : "never"
            }, ${fmtH(m.weekMs)} this week`
          );
        }
        lines.push("");
      }

      // Per-member open assignments.
      lines.push("## Open tasks by member", "");
      const byAssignee = new Map<string, Task[]>();
      for (const t of openTasks) {
        if (!t.assignee || t.kind === "milestone") continue;
        const list = byAssignee.get(t.assignee.name) ?? [];
        list.push(t);
        byAssignee.set(t.assignee.name, list);
      }
      if (byAssignee.size === 0) lines.push("_No assigned open tasks._");
      for (const [name, list] of [...byAssignee.entries()].sort()) {
        lines.push(`### ${name}`);
        for (const t of list) {
          lines.push(
            `- [${t.status}] ${t.title} — ${pname(t.projectId)}${t.phase ? ` (${t.phase})` : ""}${
              t.dueDate ? `, due ${t.dueDate}` : ""
            }`
          );
        }
        lines.push("");
      }

      // Per-project schedule + milestones + unassigned work (skip archived).
      lines.push("## Projects", "");
      for (const p of projects.filter((x) => !x.archived)) {
        const tasks = tasksByProject.get(p.id) ?? [];
        const open = tasks.filter((t) => t.status !== "done" && t.kind !== "milestone");
        const milestones = tasks.filter((t) => t.kind === "milestone");
        const unassigned = open.filter((t) => !t.assignee);
        lines.push(`### ${p.name}`);
        if (p.startDate || p.deadline) {
          lines.push(`- Schedule: ${p.startDate ?? "?"} → ${p.deadline ?? "?"}`);
        }
        lines.push(`- Open tasks: ${open.length}${unassigned.length ? ` (${unassigned.length} UNASSIGNED — candidates for standby people)` : ""}`);
        for (const m of milestones) {
          lines.push(`- Milestone: ${m.title} — ${m.dueDate ?? "no date"}${m.status === "done" ? " (done)" : ""}`);
        }
        for (const t of unassigned) {
          lines.push(`  - unassigned: ${t.title}${t.dueDate ? ` (due ${t.dueDate})` : ""}`);
        }
        lines.push("");
      }

      // Attendance history — answers "who was active last Friday" precisely.
      lines.push("## Attendance — who worked, per day (last 30 days, newest first)", "");
      if (!daily) {
        lines.push("_Attendance history unavailable at last update._", "");
      } else {
        for (const d of daily) {
          const dow = new Date(`${d.date}T00:00:00Z`).toLocaleDateString("en-US", {
            weekday: "short",
          });
          if (d.members.length === 0) {
            lines.push(`- ${d.date} (${dow}): nobody clocked in`);
          } else {
            lines.push(
              `- ${d.date} (${dow}): ` +
                d.members
                  .map((m) => `${m.name} ${fmtH(m.ms)} (${m.projects.map(pname).join(", ")})`)
                  .join(" · ")
            );
          }
        }
        lines.push("");
      }

      await fs.mkdir(path.dirname(TEAM_STATUS_PATH), { recursive: true });
      const tmp = `${TEAM_STATUS_PATH}.${process.pid}.tmp`;
      await fs.writeFile(tmp, lines.join("\n"), "utf-8");
      await fs.rename(tmp, TEAM_STATUS_PATH);
    } catch (err) {
      console.warn(
        `[team-status] update failed (retries on next tick): ${
          err instanceof Error ? err.message : "unknown"
        }`
      );
    }
  });
}

/** Debounce for task-change bursts. */
let timer: ReturnType<typeof setTimeout> | undefined;
export function scheduleTeamStatusUpdate(delayMs = 3000): void {
  clearTimeout(timer);
  timer = setTimeout(() => {
    updateTeamStatus();
  }, delayMs);
}
