"use client";

import { Artifact } from "@/lib/types";

/** fs URLs for a server-path artifact (generated file on Drive/output dir). */
function fsUrl(p: string, download = false) {
  const dir = p.slice(0, p.lastIndexOf("/")) || "/";
  const name = p.slice(p.lastIndexOf("/") + 1);
  return `/api/fs/${download ? "download" : "raw"}?root=${encodeURIComponent(dir)}&sub=${encodeURIComponent(name)}`;
}

/** Renders artifact content: live iframe for HTML, mermaid via CDN, images, code, downloads. */
export function ArtifactPreview({ artifact }: { artifact: Artifact }) {
  // Generated FILE on the server (has a path): preview via /api/fs.
  if (artifact.path) {
    const p = artifact.path;
    if (/\.(png|jpe?g|gif|webp|svg)$/i.test(p)) {
      return (
        <div className="flex items-center justify-center h-full p-4 overflow-auto">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={fsUrl(p)} alt={artifact.title} className="max-w-full max-h-full rounded-lg" />
        </div>
      );
    }
    if (/\.pdf$/i.test(p)) {
      return <iframe src={fsUrl(p)} className="w-full h-full" title={artifact.title} />;
    }
    return (
      <div className="flex flex-col items-center justify-center h-full gap-3 text-ink-faint px-6 text-center">
        <p className="text-sm">Generated by the assistant — no inline preview for this format.</p>
        <p className="text-[11px] font-mono truncate max-w-full" title={p}>
          {p}
        </p>
        <a
          href={fsUrl(p, true)}
          className="rounded-lg bg-accent px-4 py-2 text-sm text-white hover:bg-accent-hover"
        >
          Download {artifact.title}
        </a>
      </div>
    );
  }

  if (artifact.kind === "image") {
    return (
      <div className="flex items-center justify-center h-full p-4 overflow-auto">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={artifact.content}
          alt={artifact.title}
          className="max-w-full max-h-full rounded-lg"
        />
      </div>
    );
  }

  if (artifact.kind === "file") {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-3 text-ink-faint">
        <p className="text-sm">Binary file — no inline preview.</p>
        <button
          onClick={() => downloadArtifact(artifact)}
          className="rounded-lg bg-accent px-4 py-2 text-sm text-white hover:bg-accent-hover"
        >
          Download {artifact.title}
        </button>
      </div>
    );
  }

  if (artifact.kind === "html") {
    return (
      <iframe
        srcDoc={artifact.content}
        sandbox="allow-scripts"
        className="w-full h-full bg-white"
        title={artifact.title}
      />
    );
  }

  if (artifact.kind === "diagram") {
    const doc = `<!doctype html><html><body style="margin:0;display:flex;justify-content:center;padding:16px;background:white">
<pre class="mermaid">${artifact.content.replace(/</g, "&lt;")}</pre>
<script type="module">
import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";
mermaid.initialize({ startOnLoad: true });
</script></body></html>`;
    return (
      <iframe
        srcDoc={doc}
        sandbox="allow-scripts"
        className="w-full h-full bg-white"
        title={artifact.title}
      />
    );
  }

  return (
    <pre className="p-5 text-[13px] leading-relaxed whitespace-pre-wrap font-mono text-ink overflow-auto h-full">
      {artifact.content}
    </pre>
  );
}

export function downloadArtifact(artifact: Artifact) {
  // Data-URL artifacts (uploaded images/binaries) download directly.
  if (artifact.content.startsWith("data:")) {
    const a = document.createElement("a");
    a.href = artifact.content;
    a.download = artifact.title.replace(/[^\w.\- ]+/g, "_");
    a.click();
    return;
  }

  const ext =
    artifact.kind === "html"
      ? "html"
      : artifact.kind === "diagram"
        ? "mmd"
        : artifact.kind === "document"
          ? "md"
          : artifact.language || "txt";
  const name = artifact.title.includes(".") ? artifact.title : `${artifact.title}.${ext}`;
  const blob = new Blob([artifact.content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name.replace(/[^\w.\- ]+/g, "_");
  a.click();
  URL.revokeObjectURL(url);
}
